# Generated by Django 6.1 on 2026-09-02 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('capacidad', models.PositiveBigIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('creado', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(editable=False, max_length=100, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrs/')),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('usada', models.BooleanField(default=False)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usos_maximos', models.PositiveBigIntegerField(default=1)),
                ('usos_actuales', models.PositiveBigIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
        ),
    ]
