# Generated by Django 6.1 on 2026-09-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_latitud_evento_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='qr_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
