# Generated by Django 6.1 on 2026-09-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_entrada_qr_code_alter_evento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='qr_code_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrs/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
